hello_world: ./src/hello_world.cc
	mkdir build
	gcc ./src/hello_world.cc -o ./build/hello_world -lstdc++

hello_world_c: ./src/hello_world_c.c
	mkdir build
	gcc ./src/hello_world_c.c -o ./build/hello_world_c

clean:
	rm -r ./build
